[package]
name = "solana-program-stubs"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/procdump/sol-stubs.git"
readme = "README.md"

[features]
loader_stubs = []
sol_app_stubs = []
default = [ "sol_app_stubs" ]

[dependencies]
lazy_static = "1.5.0"
